const videos=[
{title:"Morning Light",category:"Nature",description:"A quiet observational film built around morning light, water and changing landscapes.",duration:"03:42",views:"1,284 views",poster:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=85",src:"https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"},
{title:"Behind the Lens",category:"Documentary",description:"A short behind-the-scenes piece about creating a visual story from raw footage.",duration:"05:18",views:"2,041 views",poster:"https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&w=1000&q=85",src:"https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"},
{title:"A Conversation About Craft",category:"Talks",description:"A studio conversation about process, craft and the decisions behind the work.",duration:"08:26",views:"1,672 views",poster:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1000&q=85",src:"https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"},
{title:"Coastal Study",category:"Nature",description:"A visual study of the coast, atmosphere and movement.",duration:"04:14",views:"983 views",poster:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=85",src:"https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"},
{title:"The First Cut",category:"Documentary",description:"From a blank timeline to a finished story: a compact editing-room journal.",duration:"06:05",views:"1,530 views",poster:"https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1000&q=85",src:"https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"},
{title:"Notes on Making",category:"Talks",description:"A short talk on creative practice, repetition and finding the useful detail.",duration:"07:11",views:"742 views",poster:"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1000&q=85",src:"https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"}];
const grid=document.getElementById('videoGrid'),playerModal=document.getElementById('playerModal'),searchModal=document.getElementById('searchModal');
function render(filter='All',query=''){const q=query.trim().toLowerCase();const list=videos.filter(v=>(filter==='All'||v.category===filter)&&(!q||[v.title,v.category,v.description].join(' ').toLowerCase().includes(q)));grid.innerHTML=list.length?list.map(v=>`<article class="video-card" data-index="${videos.indexOf(v)}"><div class="thumb"><img src="${v.poster}" alt="${v.title}"><div class="play">▶</div><div class="duration">${v.duration}</div></div><div class="card-body"><div class="eyebrow">${v.category}</div><h3>${v.title}</h3><p>${v.description}</p><div class="meta"><span>${v.views}</span><span>Cloud video</span></div></div></article>`).join(''):'<div style="color:#9fa7b1">No videos found.</div>';document.querySelectorAll('.video-card').forEach(c=>c.onclick=()=>openPlayer(+c.dataset.index))}
function openPlayer(i){const v=videos[i];const p=document.getElementById('videoPlayer');p.src=v.src;p.poster=v.poster;document.getElementById('playerCategory').textContent=v.category;document.getElementById('playerTitle').textContent=v.title;document.getElementById('playerDescription').textContent=v.description;document.getElementById('playerViews').textContent=v.views;playerModal.classList.add('show')}
function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.classList.remove('show'));document.getElementById('videoPlayer').pause()}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModals);document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter,document.getElementById('searchInput')?.value||'')});
document.getElementById('openSearch').onclick=()=>{searchModal.classList.add('show');document.getElementById('searchInput').focus();updateSearch()};document.getElementById('searchInput').oninput=updateSearch;
function updateSearch(){const q=document.getElementById('searchInput').value.toLowerCase();const list=videos.filter(v=>[v.title,v.category,v.description].join(' ').toLowerCase().includes(q));document.getElementById('searchResults').innerHTML=list.map(v=>`<div class="search-result" data-search-index="${videos.indexOf(v)}"><strong>${v.title}</strong><br><small>${v.category} · ${v.views}</small></div>`).join('');document.querySelectorAll('[data-search-index]').forEach(x=>x.onclick=()=>{closeModals();openPlayer(+x.dataset.searchIndex)})}render();
